#!/bin/bash
read OPTION
echo "content-type: text/html"
echo
if [[ $OPTION == 'add' ]] ; then
	echo "<html>"
	echo "<head>"
	echo "</head>"
	echo "<body>"
	echo 	"<form method='POST' action='./addequip.cgi'>"
        echo		"<h2>Adicionar Equipamento</h2>"
        echo		"<br><br>"
        echo		"Descrição do Equipamento:<br>"
        echo		"<input type=textbox name=name><br>"
        echo		"IP do Equipamento:<br>"
        echo		"<input type=textbox name=ip><br>"
        echo		"Usuário do Equipamento:<br>"
        echo		"<input type=textbox name=user><br>"
        echo		"Localização do Equipamento:<br>"
        echo		"<input type=textbox name=location><br><br>"
        echo		"<input type=submit value=Adicionar>"
        echo		"<input type=submit name=return value=Voltar>"
	echo	"</form>"
	echo "</body>"
	echo "</html>"
	elif [[ $OPTION == 'remove' ]] ; then
		echo "<html>"
		echo 	"<head>"
		echo 	"</head>"
		echo 	"<body>"
		echo 		"form method='POST' action='./rmvequip.cgi'>"
		echo			"<h2>Remover Equipamento</h2>"
		echo			"<br><br>"
		echo			"IP do Equipamento: <br>"
		echo			"<input type=textbox name=ip>"
		echo			"<br><br>"
		echo			"<input type=submit value=Remover>"
        	echo			"<input type=submit name=return value=Voltar>"
		echo		"</form>"
		echo 	"</body>"
		echo "</html>"
		elif [[ $OPTION == 'view' ]] ; then	
			echo "<html>"
			echo    "<head>"
			echo            "<style>"
			echo                    "table {"
			echo                            "font-family: arial, sans-serif;"
			echo                            "border-collapse: collapse;"
			echo                            "width: 100%;"
			echo                    "}"
			echo                    "td, th {"
			echo                            "border: 1px solid #dddddd;"
			echo                            "text-align: left;"
			echo                            "padding: 8px;"
			echo                    "}"
			echo                    "tr:nth-child(even) {"
			echo                            "background-color: #dddddd;"
			echo                    "}"
			echo            "</style>"
			echo    "</head>"
			echo    "<body  onload='setInterval(function() {window.location.reload();}, 5000);'>"
			echo            "<table>"
			echo                    "<tr>"
			echo                            "<th>Descrição</th>"
			echo                            "<th>Usuário</th>"
			echo                            "<th>Local</th>"
			echo                    "</tr>"
			for x in $(cat equipments.csv) ; do
				DESC=$(echo $x | cut -d";" -f1)
				USER=$(echo $x | cut -d";" -f2)
				LOC=$(echo $x | cut -d";" -f3)
				echo "<tr>"
				echo	"<td>$DESC</td>"
				echo	"<td>$USER</td>"
				echo	"<td>$LOC</td>"
				echo "</tr>"
			done
				echo		"</table>"
			echo    "</body>"
			echo "</html>"
		else
			echo "<html>"
			echo "<head>"
			echo "</head>"
			echo "<body>"
			echo "<h1><center>Erro não identificado.</center></h1>"
			echo "<a href='../equip.html'>Clique aqui para tentar novamente.</a>"
			echo "</body>"
			echo "</html>"
fi
